apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_AUTOFIX: autofix-db-service
  DB_PORT_AUTOFIX: "5432"
  DB_DBNAME_CARS: cars-db
  DB_DBNAME_REPAIR_PRICES: repair-prices-db
  DB_DBNAME_REPAIRS: repairs-db