server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://172.27.38.69:31553 # Dirección correcta del frontend
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - Authorization
              - X-Requested-With
              - Accept
            allowCredentials: true
      routes:
        - id: ms1
          uri: lb://ms1
          predicates:
            - Path=/api/v1/creditsimulation/**
        - id: ms2
          uri: lb://ms2
          predicates:
            - Path=/api/v1/users/**
        - id: ms3
          uri: lb://ms3
          predicates:
            - Path=/api/v1/creditrequests/**