server:
  port: 8080
eureka:
  instance:
    hostname: localhost #SE USA EN LOCAL
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ # #################################### cuidado con un '/' final
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        # MINUTO 44:30 DE LA AYUDANTÍA 1 DE MICROSERVICIOS
        - id: ms1
          uri: lb://ms1
          predicates:
            - Path=/api/v1/creditsimulation/**
        - id: ms2
          uri: lb://ms2
          predicates:
            - Path=/api/v1/users/**
        - id: ms3
          uri: lb://ms3
          predicates:
            - Path=/api/v1/creditrequests/**