server:
  port: 8080
eureka:
  instance:
    hostname: localhost #SE USA EN LOCAL
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # MINUTO 44:30 DE LA AYUDANTÍA 1 DE MICROSERVICIOS
        - id: ms-orders #// /////////////////////////////////////////////////////////////////////////////
          uri: lb://ms-orders #// /////////////////////////////////////////////////////////////////////////////
          predicates:
            - Path=/orders/** #// /////////////////////////////////////////////////////////////////////////////
        - id: ms-products #// /////////////////////////////////////////////////////////////////////////////
          uri: lb://ms-products #// /////////////////////////////////////////////////////////////////////////////
          predicates:
            - Path=/products/** #// /////////////////////////////////////////////////////////////////////////////