server:
  port: 8080
eureka:
  instance:
    hostname: localhost #SE USA EN LOCAL
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ # #################################### cuidado con un '/' final
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # MINUTO 44:30 DE LA AYUDANTÍA 1 DE MICROSERVICIOS
        - id: ms1
          uri: lb://ms1:8091
          predicates:
            - Path=/api/v1/creditsimulation/**
        - id: ms2
          uri: lb://ms2:8092
          predicates:
            - Path=/api/v1/user/**
        - id: ms3
          uri: lb://ms3:8093
          predicates:
            - Path=/api/v1/creditrequest/**