server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/microservicio_1
    username: postgres
    password: ${DB_PASSWORD}
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/