server:
  port: 8096
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/microservicio_6
    username: ${DB_USER}
    password: ${DB_PASSWORD}
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/