apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditsimulation-deployment
  labels:
    app: creditsimulation-deployment
spec:
  selector:
    matchLabels:
      app: creditsimulation-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: creditsimulation-deployment
    spec:
      containers:
        - name: creditsimulation
          image: juanpablocr3/creditsimulation
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_CREDITSIMULATION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_CREDITSIMULATION
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_CREDITSIMULATION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_GENERAL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_GENERAL