apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditrequest-deployment
  labels:
    app: creditrequest-deployment
spec:
  selector:
    matchLabels:
      app: creditrequest-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: creditrequest-deployment
    spec:
      containers:
        - name: creditrequest
          image: juanpablocr3/creditrequest
          ports:
            - containerPort: 8093
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_CREDITREQUEST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_CREDITREQUEST
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_CREDITREQUEST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_GENERAL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_GENERAL