apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-deployment
  labels:
    app: evaluation-deployment
spec:
  selector:
    matchLabels:
      app: evaluation-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: evaluation-deployment
    spec:
      containers:
        - name: evaluation
          image: juanpablocr3/evaluation
          ports:
            - containerPort: 8094
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_EVALUATION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_EVALUATION
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_EVALUATION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_GENERAL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_GENERAL