apiVersion: apps/v1
kind: Deployment
metadata:
  name: followup-deployment
  labels:
    app: followup-deployment
spec:
  selector:
    matchLabels:
      app: followup-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: followup-deployment
    spec:
      containers:
        - name: followup
          image: juanpablocr3/followup
          ports:
            - containerPort: 8095
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_FOLLOWUP
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_FOLLOWUP
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_FOLLOWUP
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_GENERAL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_GENERAL