--
-- PostgreSQL database dump
--

-- Dumped from database version 12.20
-- Dumped by pg_dump version 12.20

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: creditsimulation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.creditsimulation (
    id bigint NOT NULL,
    interest real NOT NULL,
    loan real NOT NULL,
    payment_quantity integer NOT NULL,
    quota real NOT NULL
);


ALTER TABLE public.creditsimulation OWNER TO postgres;

--
-- Name: creditsimulation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.creditsimulation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.creditsimulation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: creditsimulation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.creditsimulation (id, interest, loan, payment_quantity, quota) FROM stdin;
\.


--
-- Name: creditsimulation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.creditsimulation_id_seq', 1, false);


--
-- Name: creditsimulation creditsimulation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.creditsimulation
    ADD CONSTRAINT creditsimulation_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

