apiVersion: apps/v1
kind: Deployment
metadata:
  name: totalcost-deployment
  labels:
    app: totalcost-deployment
spec:
  selector:
    matchLabels:
      app: totalcost-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: totalcost-deployment
    spec:
      containers:
        - name: totalcost
          image: juanpablocr3/totalcost
          ports:
            - containerPort: 8096
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_TOTALCOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_TOTALCOST
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_TOTALCOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_GENERAL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_GENERAL